// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import CursorlightController from "./cursorlight_controller"
application.register("cursorlight", CursorlightController)

import FlatpickerController from "./flatpicker_controller"
application.register("flatpicker", FlatpickerController)

import FriendController from "./friend_controller"
application.register("friend", FriendController)

import MapController from "./map_controller"
application.register("map", MapController)

import RsvpController from "./rsvp_controller"
application.register("rsvp", RsvpController)

import SearchUsersController from "./search_users_controller"
application.register("search-users", SearchUsersController)

import SliderController from "./slider_controller"
application.register("slider", SliderController)

import TomSelectController from "./tom_select_controller"
application.register("tom-select", TomSelectController)
